CREATE TABLE Pessoa(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    cpf VARCHAR2(11) UNIQUE,
    data_nascimento DATE,
    sexo VARCHAR2(9),
    tipo VARCHAR2(11),
    CHECK(sexo IN ('Masculino', 'Feminino', 'Outro')),
    CHECK(tipo IN ('Familiar', 'Funcionario', 'Falecido'))
);

CREATE TABLE Funcionario(
    id INT PRIMARY KEY,
    data_contratacao DATE DEFAULT SYSDATE,
    funcao VARCHAR2(50),
    salario NUMBER(8, 2),
    CONSTRAINT fk_funcionario_pessoa FOREIGN KEY(id) REFERENCES Pessoa(id)
);

CREATE TABLE Falecido(
    id INT PRIMARY KEY,
    data_falecimento DATE,
    causa_obito VARCHAR2(50),
    numero_documento_obito VARCHAR2(50) UNIQUE,
    CONSTRAINT fk_falecido_pessoa FOREIGN KEY(id) REFERENCES Pessoa(id)
);

CREATE TABLE Familiar(
    id INT PRIMARY KEY,
    CONSTRAINT fk_familiar_pessoa FOREIGN KEY(id) REFERENCES Pessoa(id)
);

CREATE TABLE Endereco(
    cep VARCHAR2(8) PRIMARY KEY,
    estado CHAR(2),
    cidade VARCHAR2(50),
    bairro VARCHAR2(50),
    rua VARCHAR2(100)
);

CREATE TABLE Telefone(
    numero VARCHAR2(13) PRIMARY KEY
);

CREATE TABLE Jazigo(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fila INT,
    quadra INT,
    numero INT,
    capacidade INT,
    tipo VARCHAR2(20)
);

CREATE TABLE ServicoFunerario(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(20),
    valor NUMBER(8, 2),
    data DATE
);

CREATE TABLE ResponsabilidadeJazigo(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jazigo_id INT,
    responsavel_id INT,
    pagamento NUMBER(8, 2),
    aluguel NUMBER(8, 2),
    data_inicio DATE DEFAULT SYSDATE,
    data_fim DATE,
    CONSTRAINT fk_responsabilidade_jazigo FOREIGN KEY(jazigo_id) REFERENCES Jazigo(id),
    CONSTRAINT fk_responsabilidade_familiar FOREIGN KEY(responsavel_id) REFERENCES Familiar(id)
);

CREATE TABLE ManutencaoJazigo(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jazigo_id INT,
    funcionario_id INT,
    data_inicio DATE DEFAULT SYSDATE,
    data_fim DATE,
    motivo VARCHAR2(500),
    CONSTRAINT fk_manutencao_jazigo FOREIGN KEY(jazigo_id) REFERENCES Jazigo(id),
    CONSTRAINT fk_manutencao_funcionario FOREIGN KEY(funcionario_id) REFERENCES Funcionario(id)
);

CREATE TABLE OcorrenciaManutecao(
    manutencao_id INT,
    data_ocorrencia DATE DEFAULT SYSDATE,
    descricao VARCHAR2(500),
    PRIMARY KEY(manutencao_id, data_ocorrencia),
    CONSTRAINT fk_ocorrencia_manutencao FOREIGN KEY(manutencao_id) REFERENCES ManutencaoJazigo(id)
);

CREATE TABLE Material(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    descricao VARCHAR2(500)
);
